# make a decision as to what sort of settings file should be used 
# https://stackoverflow.com/questions/5055042/whats-the-best-practice-using-a-settings-file-in-python
# https://camel.readthedocs.io/en/latest/yamlref.html

omitted_paths:
language: net
root_check_enabled: True